# Generated by Django 6.0.4 on 2026-04-21 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0002_add_condition_groups_and_cross_indicator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100, verbose_name='Название стратегии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запуска')),
                ('tickers_analyzed', models.IntegerField(default=0, verbose_name='Тикеров проверено')),
                ('tickers_matched', models.IntegerField(default=0, verbose_name='Тикеров прошло')),
                ('matched_tickers', models.JSONField(default=list, verbose_name='Прошедшие тикеры')),
                ('details', models.JSONField(default=list, verbose_name='Подробности')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='strategies.strategy', verbose_name='Стратегия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запуск анализа',
                'verbose_name_plural': 'История анализов',
                'ordering': ['-created_at'],
            },
        ),
    ]
