services:
  init_keys:
    image: python:3.12-slim
    working_dir: /project
    environment:
      - JWT_KEYS_DIR=/app/keys
    command: >
      sh -c "pip install cryptography && python generate_keys.py"
    volumes:
      - .:/project
      - jwt_keys:/app/keys

  django:
    build:
      context: ./django_service
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      init_keys:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - internal
    volumes:
      - jwt_keys:/app/keys
  fastapi:
    build:
      context: ./fastapi_service
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8001:8001"
    depends_on:
      init_keys:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - internal
    volumes:
      - jwt_keys:/app/keys

  celery_worker:
    build:
      context: ./fastapi_service
      dockerfile: Dockerfile
    command: celery -A worker.celery_app worker --loglevel=info -c 4
    env_file: .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      init_keys:
        condition: service_completed_successfully
      redis:
        condition: service_started
    networks:
      - internal
    volumes:
      - jwt_keys:/app/keys

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:7
    networks:
      - internal
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  jwt_keys: