# Generated by Django 6.0.4 on 2026-04-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategycondition',
            options={'ordering': ['group_id', 'id'], 'verbose_name': 'Условие стратегии', 'verbose_name_plural': 'Условия стратегии'},
        ),
        migrations.AddField(
            model_name='strategycondition',
            name='compare_to_indicator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сравнить с индикатором'),
        ),
        migrations.AddField(
            model_name='strategycondition',
            name='compare_to_params',
            field=models.JSONField(blank=True, null=True, verbose_name='Параметры второго индикатора'),
        ),
        migrations.AddField(
            model_name='strategycondition',
            name='group_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID OR-группы'),
        ),
        migrations.AddField(
            model_name='strategycondition',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Обязательное условие (MUST)'),
        ),
        migrations.AddField(
            model_name='strategycondition',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя условия'),
        ),
    ]
